version: "3.7"

networks:
  springlab:
    driver: bridge

services:
  mysql:
    image: mysql:5.7.8
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    ports:
      - "3306:3306"
    networks:
      - springlab

  petclinic:
    image: romuloslv/petclinic
    container_name: petclinic
    hostname: petclinic
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - springlab
